version: 2

build:
  os: "ubuntu-20.04"
  tools:
    python: "3.6"

sphinx:
  builder: dirhtml
  configuration: docs/source/conf.py

python:
  install:
    - requirements: docs/source/requirements.txt
